name: run
services:
  members-registered-interests-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - db_data:/app/data/members.db
    image: members-registered-interests-mcp:1
    ports:
      - "8000:8000"
    command: uv run uvicorn app.api_server:app --host 0.0.0.0 --port 8000

volumes:
  db_data: