# generated by datamodel-codegen:
#   filename:  members.json
#   timestamp: 2025-08-01T12:45:05+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class BiographyExperience(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    type: Optional[str] = None
    typeId: Optional[int] = None
    title: Optional[str] = None
    organisation: Optional[str] = None
    startMonth: Optional[int] = None
    startYear: Optional[int] = None
    endMonth: Optional[int] = None
    endYear: Optional[int] = None


class ContactInformation(BaseModel):
    class Config:
        extra = "forbid"

    type: Optional[str] = None
    typeDescription: Optional[str] = None
    typeId: Optional[int] = None
    isPreferred: Optional[bool] = None
    isWebAddress: Optional[bool] = None
    notes: Optional[str] = None
    line1: Optional[str] = None
    line2: Optional[str] = None
    line3: Optional[str] = None
    line4: Optional[str] = None
    line5: Optional[str] = None
    postcode: Optional[str] = None
    phone: Optional[str] = None
    fax: Optional[str] = None
    email: Optional[str] = None
    website: Optional[str] = None


class DebateContribution(BaseModel):
    class Config:
        extra = "forbid"

    totalContributions: Optional[int] = None
    debateTitle: Optional[str] = None
    debateId: Optional[int] = None
    debateWebsiteId: Optional[str] = None
    sittingDate: Optional[datetime] = None
    section: Optional[str] = None
    house: Optional[str] = None
    firstTimecode: Optional[datetime] = None
    speechCount: Optional[int] = None
    questionCount: Optional[int] = None
    supplementaryQuestionCount: Optional[int] = None
    interventionCount: Optional[int] = None
    answerCount: Optional[int] = None
    pointsOfOrderCount: Optional[int] = None
    statementsCount: Optional[int] = None


class EarlyDayMotion(BaseModel):
    class Config:
        extra = "forbid"

    title: Optional[str] = None
    number: Optional[str] = None
    isPrayer: Optional[bool] = None
    isAmendment: Optional[bool] = None
    id: Optional[int] = None
    dateTabled: Optional[datetime] = None
    sponsorsCount: Optional[int] = None


class GenericReferenceData(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    description: Optional[str] = None


class GovernmentDepartment(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    name: Optional[str] = None
    url: Optional[str] = None
    imageUrl: Optional[str] = None


class GovernmentType(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class GroupedQuestion(BaseModel):
    class Config:
        extra = "forbid"

    questionUin: Optional[str] = None
    dateTabled: Optional[datetime] = None


class House(Enum):
    integer_1 = 1
    integer_2 = 2


class Link(BaseModel):
    class Config:
        extra = "forbid"

    rel: Optional[str] = None
    href: Optional[str] = None
    method: Optional[str] = None


class LocationType(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class MatchedBy(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_4 = 4
    integer_8 = 8
    integer_16 = 16
    integer_32 = 32
    integer_64 = 64
    integer_128 = 128
    integer_256 = 256
    integer_512 = 512
    integer_1024 = 1024
    integer_2048 = 2048
    integer_4096 = 4096
    integer_8192 = 8192


class MemberFocus(BaseModel):
    class Config:
        extra = "forbid"

    category: Optional[str] = None
    focus: Optional[List[str]] = None


class MemberFocusListItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[List[MemberFocus]] = None
    links: Optional[List[Link]] = None


class MemberName(BaseModel):
    class Config:
        extra = "forbid"

    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None
    nameListAs: Optional[str] = None
    nameDisplayAs: Optional[str] = None
    nameFullTitle: Optional[str] = None
    nameAddressAs: Optional[str] = None


class MemberStatus(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class Party(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    name: Optional[str] = None
    abbreviation: Optional[str] = None
    backgroundColour: Optional[str] = None
    foregroundColour: Optional[str] = None
    isLordsMainParty: Optional[bool] = None
    isLordsSpiritualParty: Optional[bool] = None
    governmentType: Optional[GovernmentType] = None
    isIndependentParty: Optional[bool] = None


class PartyItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[Party] = None
    links: Optional[List[Link]] = None


class PartyMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[PartyItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class PartySeatCount(BaseModel):
    class Config:
        extra = "forbid"

    male: Optional[int] = None
    female: Optional[int] = None
    nonBinary: Optional[int] = None
    total: Optional[int] = None
    party: Optional[Party] = None


class PartySeatCountItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[PartySeatCount] = None
    links: Optional[List[Link]] = None


class PartySeatCountMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[PartySeatCountItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class PortraitCropEnum(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class PostType(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2


class RegisteredInterest(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    interest: Optional[str] = None
    createdWhen: Optional[datetime] = None
    lastAmendedWhen: Optional[datetime] = None
    deletedWhen: Optional[datetime] = None
    isCorrection: Optional[bool] = None
    childInterests: Optional[List[RegisteredInterest]] = None


class RegisteredInterestCategory(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    name: Optional[str] = None
    sortOrder: Optional[int] = None
    interests: Optional[List[RegisteredInterest]] = None


class RegisteredInterestCategoryListItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[List[RegisteredInterestCategory]] = None
    links: Optional[List[Link]] = None


class RepresentationItem(BaseModel):
    class Config:
        extra = "forbid"

    house: Optional[House] = None
    name: Optional[str] = None
    id: Optional[int] = None
    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None
    additionalInfo: Optional[str] = None
    additionalInfoLink: Optional[str] = None
    constituencyStart: Optional[datetime] = None
    constituencyEnd: Optional[datetime] = None


class Staff(BaseModel):
    class Config:
        extra = "forbid"

    surname: Optional[str] = None
    forename: Optional[str] = None
    title: Optional[str] = None
    details: Optional[str] = None


class StaffListItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[List[Staff]] = None
    links: Optional[List[Link]] = None


class StringItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[str] = None
    links: Optional[List[Link]] = None


class Vote(BaseModel):
    class Config:
        extra = "forbid"

    house: Optional[House] = None
    id: Optional[int] = None
    inAffirmativeLobby: Optional[bool] = None
    actedAsTeller: Optional[bool] = None
    title: Optional[str] = None
    date: Optional[datetime] = None
    divisionNumber: Optional[int] = None
    numberInFavour: Optional[int] = None
    numberAgainst: Optional[int] = None


class VoteItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[Vote] = None
    links: Optional[List[Link]] = None


class VoteMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[VoteItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class AnsweringBody(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    name: Optional[str] = None
    shortName: Optional[str] = None
    target: Optional[str] = None
    department: Optional[GovernmentDepartment] = None


class BiographyExperienceListItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[List[BiographyExperience]] = None
    links: Optional[List[Link]] = None


class BiographyItem(BaseModel):
    class Config:
        extra = "forbid"

    house: Optional[House] = None
    name: Optional[str] = None
    id: Optional[int] = None
    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None
    additionalInfo: Optional[str] = None
    additionalInfoLink: Optional[str] = None


class ContactInformationListItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[List[ContactInformation]] = None
    links: Optional[List[Link]] = None


class DebateContributionItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[DebateContribution] = None
    links: Optional[List[Link]] = None


class DebateContributionMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[DebateContributionItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class EarlyDayMotionItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[EarlyDayMotion] = None
    links: Optional[List[Link]] = None


class EarlyDayMotionMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[EarlyDayMotionItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class ElectionCandidate(BaseModel):
    class Config:
        extra = "forbid"

    memberId: Optional[int] = None
    name: Optional[str] = None
    party: Optional[Party] = None
    resultChange: Optional[str] = None
    rankOrder: Optional[int] = None
    votes: Optional[int] = None
    voteShare: Optional[float] = None


class ElectionResult(BaseModel):
    class Config:
        extra = "forbid"

    result: Optional[str] = None
    isNotional: Optional[bool] = None
    electorate: Optional[int] = None
    turnout: Optional[int] = None
    majority: Optional[int] = None
    winningParty: Optional[Party] = None
    electionTitle: Optional[str] = None
    electionDate: Optional[datetime] = None
    electionId: Optional[int] = None
    isGeneralElection: Optional[bool] = None
    constituencyName: Optional[str] = None
    candidates: Optional[List[ElectionCandidate]] = None


class ElectionResultItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[ElectionResult] = None
    links: Optional[List[Link]] = None


class ElectionResultListItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[List[ElectionResult]] = None
    links: Optional[List[Link]] = None


class HouseMembershipStatus(BaseModel):
    class Config:
        extra = "forbid"

    statusIsActive: Optional[bool] = None
    statusDescription: Optional[str] = None
    statusNotes: Optional[str] = None
    statusId: Optional[int] = None
    status: Optional[MemberStatus] = None
    statusStartDate: Optional[datetime] = None


class LocationContext(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    name: Optional[str] = None
    type: Optional[LocationType] = None
    typeName: Optional[str] = None


class LordsByType(BaseModel):
    class Config:
        extra = "forbid"

    life: Optional[int] = None
    hereditary: Optional[int] = None
    bishop: Optional[int] = None
    total: Optional[int] = None
    party: Optional[Party] = None


class LordsByTypeItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[LordsByType] = None
    links: Optional[List[Link]] = None


class LordsByTypeMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[LordsByTypeItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class MemberBiography(BaseModel):
    class Config:
        extra = "forbid"

    representations: Optional[List[RepresentationItem]] = None
    electionsContested: Optional[List[BiographyItem]] = None
    houseMemberships: Optional[List[BiographyItem]] = None
    governmentPosts: Optional[List[BiographyItem]] = None
    oppositionPosts: Optional[List[BiographyItem]] = None
    otherPosts: Optional[List[BiographyItem]] = None
    partyAffiliations: Optional[List[BiographyItem]] = None
    committeeMemberships: Optional[List[BiographyItem]] = None


class MemberBiographyItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[MemberBiography] = None
    links: Optional[List[Link]] = None


class MemberParty(BaseModel):
    class Config:
        extra = "forbid"

    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None
    party: Optional[Party] = None


class HouseMembership(BaseModel):
    class Config:
        extra = "forbid"

    membershipFrom: Optional[str] = None
    membershipFromId: Optional[int] = None
    house: Optional[House] = None
    membershipStartDate: Optional[datetime] = None
    membershipEndDate: Optional[datetime] = None
    membershipEndReason: Optional[str] = None
    membershipEndReasonNotes: Optional[str] = None
    membershipEndReasonId: Optional[int] = None
    membershipStatus: Optional[HouseMembershipStatus] = None


class Location(BaseModel):
    class Config:
        extra = "forbid"

    context: Optional[LocationContext] = None
    parentContext: Optional[LocationContext] = None
    childContexts: Optional[List[LocationContext]] = None
    stateOfTheParties: Optional[List[PartySeatCount]] = None


class LocationItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[Location] = None
    links: Optional[List[Link]] = None


class Member(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    nameListAs: Optional[str] = None
    nameDisplayAs: Optional[str] = None
    nameFullTitle: Optional[str] = None
    nameAddressAs: Optional[str] = None
    latestParty: Optional[Party] = None
    gender: Optional[str] = None
    latestHouseMembership: Optional[HouseMembership] = None
    thumbnailUrl: Optional[str] = None


class MemberHistory(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    thumbnailUrl: Optional[str] = None
    partyHistory: Optional[List[MemberParty]] = None
    houseMembershipHistory: Optional[List[HouseMembership]] = None
    nameHistory: Optional[List[MemberName]] = None


class MemberHistoryItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[MemberHistory] = None
    links: Optional[List[Link]] = None


class MemberItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[Member] = None
    links: Optional[List[Link]] = None


class MemberMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[MemberItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class MembersInterests(BaseModel):
    class Config:
        extra = "forbid"

    member: Optional[Member] = None
    interestCategories: Optional[List[RegisteredInterestCategory]] = None


class MembersInterestsItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[MembersInterests] = None
    links: Optional[List[Link]] = None


class MembersInterestsMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[MembersInterestsItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class MembersStaff(BaseModel):
    class Config:
        extra = "forbid"

    member: Optional[Member] = None
    staff: Optional[List[Staff]] = None


class MembersStaffItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[MembersStaff] = None
    links: Optional[List[Link]] = None


class MembersStaffMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[MembersStaffItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class WrittenQuestion(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    askingMemberId: Optional[int] = None
    house: Optional[House] = None
    memberHasInterest: Optional[bool] = None
    dateTabled: Optional[datetime] = None
    dateForAnswer: Optional[datetime] = None
    uin: Optional[str] = None
    questionText: Optional[str] = None
    answeringBodyId: Optional[int] = None
    isWithdrawn: Optional[bool] = None
    isNamedDay: Optional[bool] = None
    groupedQuestions: Optional[List[str]] = None
    groupedQuestionsDates: Optional[List[GroupedQuestion]] = None
    answerIsHolding: Optional[bool] = None
    answerIsCorrection: Optional[bool] = None
    answeringMemberId: Optional[int] = None
    correctingMemberId: Optional[int] = None
    dateAnswered: Optional[datetime] = None
    answerText: Optional[str] = None
    attachmentCount: Optional[int] = None
    heading: Optional[str] = None
    answeringMember: Optional[Member] = None
    correctingMember: Optional[Member] = None
    answeringBody: Optional[AnsweringBody] = None


class WrittenQuestionItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[WrittenQuestion] = None
    links: Optional[List[Link]] = None


class WrittenQuestionMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[WrittenQuestionItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class ConstituencyRepresentation(BaseModel):
    class Config:
        extra = "forbid"

    member: Optional[MemberItem] = None
    representation: Optional[HouseMembership] = None


class ConstituencyRepresentationListItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[List[ConstituencyRepresentation]] = None
    links: Optional[List[Link]] = None


class GovernmentOppositionPostHolder(BaseModel):
    class Config:
        extra = "forbid"

    member: Optional[MemberItem] = None
    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None
    layingMinisterName: Optional[str] = None
    isPaid: Optional[bool] = None


class Constituency(BaseModel):
    class Config:
        extra = "forbid"

    id: Optional[int] = None
    name: Optional[str] = None
    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None
    currentRepresentation: Optional[ConstituencyRepresentation] = None


class ConstituencyItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[Constituency] = None
    links: Optional[List[Link]] = None


class ConstituencyMembersServiceSearchResult(BaseModel):
    class Config:
        extra = "forbid"

    items: Optional[List[ConstituencyItem]] = None
    totalResults: Optional[int] = None
    resultContext: Optional[str] = None
    skip: Optional[int] = None
    take: Optional[int] = None
    links: Optional[List[Link]] = None
    resultType: Optional[MatchedBy] = None


class GovernmentOppositionPost(BaseModel):
    class Config:
        extra = "forbid"

    type: Optional[PostType] = None
    name: Optional[str] = None
    hansardName: Optional[str] = None
    id: Optional[int] = None
    postHolders: Optional[List[GovernmentOppositionPostHolder]] = None
    governmentDepartments: Optional[List[GovernmentDepartment]] = None
    createdWhen: Optional[datetime] = None
    order: Optional[int] = None


class GovernmentOppositionPostItem(BaseModel):
    class Config:
        extra = "forbid"

    value: Optional[GovernmentOppositionPost] = None
    links: Optional[List[Link]] = None


RegisteredInterest.update_forward_refs()
